title: Marcus Diedrich: A Day in the Life
author: TRUB DUBZ
email: marcusdiedrich1@icloud.com
description: > # this means to ignore newlines until "baseurl"
a demo website to further develop my skills as a Developer.

# social links
twitter_username: MarcusDiedrich1 # DO NOT include the @ character, or else the build will fail!
github_username:  TRUBDUBZ # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
